# Generated by Django 4.0.4 on 2022-05-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Data',
        ),
    ]
