# Generated by Django 3.2.13 on 2022-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_rename_publications_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
