# Generated by Django 3.2.13 on 2022-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='purpose',
            field=models.CharField(max_length=1000, verbose_name='Zweck'),
        ),
    ]
